In [2]:
import pandas as pd
headers = ["name","landmass","zone","area","population","language","religion","bars","stripes","colours","red","green","blue","gold","white","black","orange","mainhue","circles","crosses","saltires","quarters","sunstars","crescent","triangle","icon","animate","text","topleft","botright"]
tabla = pd.read_csv("resource/flag.data",names=headers)

In [3]:
pd.options.display.max_columns = 2000
#pd.options.display.max_rows = 200

tabla

,name,landmass,zone,area,population,language,religion,bars,stripes,colours,red,green,blue,gold,white,black,orange,mainhue,circles,crosses,saltires,quarters,sunstars,crescent,triangle,icon,animate,text,topleft,botright
0,Afghanistan,5,1,648,16,10,2,0,3,5,1,1,0,1,1,1,0,green,0,0,0,0,1,0,0,1,0,0,black,green
1,Albania,3,1,29,3,6,6,0,0,3,1,0,0,1,0,1,0,red,0,0,0,0,1,0,0,0,1,0,red,red
2,Algeria,4,1,2388,20,8,2,2,0,3,1,1,0,0,1,0,0,green,0,0,0,0,1,1,0,0,0,0,green,white
3,American-Samoa,6,3,0,0,1,1,0,0,5,1,0,1,1,1,0,1,blue,0,0,0,0,0,0,1,1,1,0,blue,red
4,Andorra,3,1,0,0,6,0,3,0,3,1,0,1,1,0,0,0,gold,0,0,0,0,0,0,0,0,0,0,blue,red
5,Angola,4,2,1247,7,10,5,0,2,3,1,0,0,1,0,1,0,red,0,0,0,0,1,0,0,1,0,0,red,black
6,Anguilla,1,4,0,0,1,1,0,1,3,0,0,1,0,1,0,1,white,0,0,0,0,0,0,0,0,1,0,white,blue
7,Antigua-Barbuda,1,4,0,0,1,1,0,1,5,1,0,1,1,1,1,0,red,0,0,0,0,1,0,1,0,0,0,black,red
8,Argentina,2,3,2777,28,2,0,0,3,2,0,0,1,0,1,0,0,blue,0,0,0,0,0,0,0,0,0,0,blue,blue
9,Argentine,2,3,2777,28,2,0,0,3,3,0,0,1,1,1,0,0,blue,0,0,0,0,1,0,0,0,0,0,blue,blue
10,Australia,6,2,7690,15,1,1,0,0,3,1,0,1,0,1,0,0,blue,0,1,1,1,6,0,0,0,0,0,white,blue
11,Austria,3,1,84,8,4,0,0,3,2,1,0,0,0,1,0,0,red,0,0,0,0,0,0,0,0,0,0,red,red
12,Bahamas,1,4,19,0,1,1,0,3,3,0,0,1,1,0,1,0,blue,0,0,0,0,0,0,1,0,0,0,blue,blue
13,Bahrain,5,1,1,0,8,2,0,0,2,1,0,0,0,1,0,0,red,0,0,0,0,0,0,0,0,0,0,white,red
14,Bangladesh,5,1,143,90,6,2,0,0,2,1,1,0,0,0,0,0,green,1,0,0,0,0,0,0,0,0,0,green,green
15,Barbados,1,4,0,0,1,1,3,0,3,0,0,1,1,0,1,0,blue,0,0,0,0,0,0,0,1,0,0,blue,blue
16,Belgium,3,1,31,10,6,0,3,0,3,1,0,0,1,0,1,0,gold,0,0,0,0,0,0,0,0,0,0,black,red
17,Belize,1,4,23,0,1,1,0,2,8,1,1,1,1,1,1,1,blue,1,0,0,0,0,0,0,1,1,1,red,red
18,Benin,4,1,113,3,3,5,0,0,2,1,1,0,0,0,0,0,green,0,0,0,0,1,0,0,0,0,0,green,green
19,Bermuda,1,4,0,0,1,1,0,0,6,1,1,1,1,1,1,0,red,1,1,1,1,0,0,0,1,1,0,white,red
20,Bhutan,5,1,47,1,10,3,0,0,4,1,0,0,0,1,1,1,orange,4,0,0,0,0,0,0,0,1,0,orange,red
21,Bolivia,2,3,1099,6,2,0,0,3,3,1,1,0,1,0,0,0,red,0,0,0,0,0,0,0,0,0,0,red,green
22,Botswana,4,2,600,1,10,5,0,5,3,0,0,1,0,1,1,0,blue,0,0,0,0,0,0,0,0,0,0,blue,blue
23,Brazil,2,3,8512,119,6,0,0,0,4,0,1,1,1,1,0,0,green,1,0,0,0,22,0,0,0,0,1,green,green
24,British-Virgin-Isles,1,4,0,0,1,1,0,0,6,1,1,1,1,1,0,1,blue,0,1,1,1,0,0,0,1,1,1,white,blue
25,Brunei,5,1,6,0,10,2,0,0,4,1,0,0,1,1,1,0,gold,0,0,0,0,0,0,1,1,1,1,white,gold
26,Bulgaria,3,1,111,9,5,6,0,3,5,1,1,1,1,1,0,0,red,0,0,0,0,1,0,0,1,1,0,white,red
27,Burkina,4,4,274,7,3,5,0,2,3,1,1,0,1,0,0,0,red,0,0,0,0,1,0,0,0,0,0,red,green
28,Burma,5,1,678,35,10,3,0,0,3,1,0,1,0,1,0,0,red,0,0,0,1,14,0,0,1,1,0,blue,red
29,Burundi,4,2,28,4,10,5,0,0,3,1,1,0,0,1,0,0,red,1,0,1,0,3,0,0,0,0,0,white,white
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,Swaziland,4,2,17,1,10,1,0,5,7,1,0,1,1,1,1,1,blue,0,0,0,0,0,0,0,1,0,0,blue,blue
165,Sweden,3,1,450,8,6,1,0,0,2,0,0,1,1,0,0,0,blue,0,1,0,0,0,0,0,0,0,0,blue,blue
166,Switzerland,3,1,41,6,4,1,0,0,2,1,0,0,0,1,0,0,red,0,1,0,0,0,0,0,0,0,0,red,red
167,Syria,5,1,185,10,8,2,0,3,4,1,1,0,0,1,1,0,red,0,0,0,0,2,0,0,0,0,0,red,black
168,Taiwan,5,1,36,18,7,3,0,0,3,1,0,1,0,1,0,0,red,1,0,0,1,1,0,0,0,0,0,blue,red
169,Tanzania,4,2,945,18,10,5,0,0,4,0,1,1,1,0,1,0,green,0,0,0,0,0,0,1,0,0,0,green,blue
170,Thailand,5,1,514,49,10,3,0,5,3,1,0,1,0,1,0,0,red,0,0,0,0,0,0,0,0,0,0,red,red
171,Togo,4,1,57,2,3,7,0,5,4,1,1,0,1,1,0,0,green,0,0,0,1,1,0,0,0,0,0,red,green
172,Tonga,6,2,1,0,10,1,0,0,2,1,0,0,0,1,0,0,red,0,1,0,1,0,0,0,0,0,0,white,red
173,Trinidad-Tobago,2,4,5,1,1,1,0,0,3,1,0,0,0,1,1,0,red,0,0,0,0,0,0,1,0,0,0,white,white
174,Tunisia,4,1,164,7,8,2,0,0,2,1,0,0,0,1,0,0,red,1,0,0,0,1,1,0,0,0,0,red,red
175,Turkey,5,1,781,45,9,2,0,0,2,1,0,0,0,1,0,0,red,0,0,0,0,1,1,0,0,0,0,red,red
176,Turks-Cocos-Islands,1,4,0,0,1,1,0,0,6,1,1,1,1,1,0,1,blue,0,1,1,1,0,0,0,1,1,0,white,blue
177,Tuvalu,6,2,0,0,1,1,0,0,5,1,0,1,1,1,0,0,blue,0,1,1,1,9,0,0,0,0,0,white,blue
178,UAE,5,1,84,1,8,2,1,3,4,1,1,0,0,1,1,0,green,0,0,0,0,0,0,0,0,0,0,red,black
179,Uganda,4,1,236,13,10,5,0,6,5,1,0,0,1,1,1,0,gold,1,0,0,0,0,0,0,0,1,0,black,red
180,UK,3,4,245,56,1,1,0,0,3,1,0,1,0,1,0,0,red,0,1,1,0,0,0,0,0,0,0,white,red
181,Uruguay,2,3,178,3,2,0,0,9,3,0,0,1,1,1,0,0,white,0,0,0,1,1,0,0,0,0,0,white,white
182,US-Virgin-Isles,1,4,0,0,1,1,0,0,6,1,1,1,1,1,0,0,white,0,0,0,0,0,0,0,1,1,1,white,white
183,USA,1,4,9363,231,1,1,0,13,3,1,0,1,0,1,0,0,white,0,0,0,1,50,0,0,0,0,0,blue,red
184,USSR,5,1,22402,274,5,6,0,0,2,1,0,0,1,0,0,0,red,0,0,0,0,1,0,0,1,0,0,red,red
185,Vanuatu,6,2,15,0,6,1,0,0,4,1,1,0,1,0,1,0,red,0,0,0,0,0,0,1,0,1,0,black,green
186,Vatican-City,3,1,0,0,6,0,2,0,4,1,0,0,1,1,1,0,gold,0,0,0,0,0,0,0,1,0,0,gold,white
187,Venezuela,2,4,912,15,2,0,0,3,7,1,1,1,1,1,1,1,red,0,0,0,0,7,0,0,1,1,0,gold,red
188,Vietnam,5,1,333,60,10,6,0,0,2,1,0,0,1,0,0,0,red,0,0,0,0,1,0,0,0,0,0,red,red
189,Western-Samoa,6,3,3,0,1,1,0,0,3,1,0,1,0,1,0,0,red,0,0,0,1,5,0,0,0,0,0,blue,red
190,Yugoslavia,3,1,256,22,6,6,0,3,4,1,0,1,1,1,0,0,red,0,0,0,0,1,0,0,0,0,0,blue,red
191,Zaire,4,2,905,28,10,5,0,0,4,1,1,0,1,0,0,1,green,1,0,0,0,0,0,0,1,1,0,green,green
192,Zambia,4,2,753,6,10,5,3,0,4,1,1,0,0,0,1,1,green,0,0,0,0,0,0,0,0,1,0,green,brown
193,Zimbabwe,4,2,391,8,10,5,0,7,5,1,1,0,1,1,1,0,green,0,0,0,0,1,0,1,1,1,0,green,green

In [4]:
tabla[(tabla["landmass"] == 5) & (tabla["name"] =="Afghanistan")]

,name,landmass,zone,area,population,language,religion,bars,stripes,colours,red,green,blue,gold,white,black,orange,mainhue,circles,crosses,saltires,quarters,sunstars,crescent,triangle,icon,animate,text,topleft,botright
0,Afghanistan,5,1,648,16,10,2,0,3,5,1,1,0,1,1,1,0,green,0,0,0,0,1,0,0,1,0,0,black,green

In [5]:
len(tabla[(tabla["landmass"] == 5)])

39

In [6]:
tabla["religion"].value_counts()

1    60
0    40
2    36
5    27
6    15
3     8
7     4
4     4
Name: religion, dtype: int64

In [7]:
len(tabla["religion"])

194

In [8]:
tabla.sample(n=2)

,name,landmass,zone,area,population,language,religion,bars,stripes,colours,red,green,blue,gold,white,black,orange,mainhue,circles,crosses,saltires,quarters,sunstars,crescent,triangle,icon,animate,text,topleft,botright
185,Vanuatu,6,2,15,0,6,1,0,0,4,1,1,0,1,0,1,0,red,0,0,0,0,0,0,1,0,1,0,black,green
182,US-Virgin-Isles,1,4,0,0,1,1,0,0,6,1,1,1,1,1,0,0,white,0,0,0,0,0,0,0,1,1,1,white,white

In [25]:
tabla.sample(n=2, axis=1)[:5]

   crescent  orange
0         0       0
1         0       0
2         1       0
3         0       1
4         0       0

In [22]:
total = tabla["area"].count()
total

194

In [11]:
cantidad = tabla["area"].value_counts().sort_index()
cantidad

0        34
1         6
2         2
3         2
4         2
5         1
6         1
9         2
10        2
11        2
12        1
15        1
17        1
18        2
19        1
21        2
22        1
23        1
26        1
28        3
29        1
30        2
31        1
36        2
41        2
43        1
47        1
49        1
51        1
57        1
         ..
925       1
945       1
1001      1
1031      1
1099      1
1139      1
1221      1
1222      1
1240      1
1247      1
1267      1
1284      1
1285      1
1566      1
1648      1
1760      1
1904      1
1973      1
2150      1
2176      1
2388      1
2506      1
2777      2
3268      1
7690      1
8512      1
9363      1
9561      1
9976      1
22402     1
Name: area, Length: 136, dtype: int64

In [12]:
len(cantidad)

136

In [13]:
grouped = tabla[["area","religion"]].groupby(["area","religion"])
for t in grouped:
    print(t)

((0, 0),      area  religion
4       0         0
101     0         0
108     0         0
114     0         0
144     0         0
145     0         0
186     0         0)
((0, 1),      area  religion
3       0         1
6       0         1
7       0         1
15      0         1
19      0         1
24      0         1
33      0         1
41      0         1
48      0         1
67      0         1
70      0         1
71      0         1
94      0         1
109     0         1
116     0         1
119     0         1
122     0         1
127     0         1
148     0         1
158     0         1
159     0         1
160     0         1
161     0         1
176     0         1
177     0         1
182     0         1)
((0, 2),      area  religion
106     0         2)
((1, 1),      area  religion
55      1         1
113     1         1
172     1         1)
((1, 2),     area  religion
13     1         2)
((1, 3),      area  religion
78      1         3
150     1         3)
((2, 2),     area  religion
39     2         2)
((2, 4),      area  religion
111     2         4)
((3, 0),      area  religion
102     3         0)
((3, 1),      area  religion
189     3         1)
((4, 0),     area  religion
32     4         0
61     4         0)
((5, 1),      area  religion
173     5         1)
((6, 2),     area  religion
25     6         2)
((9, 0),      area  religion
140     9         0)
((9, 1),     area  religion
44     9         1)
((10, 2),     area  religion
97    10         2)
((10, 5),     area  religion
63    10         5)
((11, 1),     area  religion
89    11         1)
((11, 2),      area  religion
141    11         2)
((12, 1),     area  religion
56    12         1)
((15, 1),      area  religion
185    15         1)
((17, 1),      area  religion
164    17         1)
((18, 1),     area  religion
57    18         1)
((18, 2),     area  religion
95    18         2)
((19, 1),     area  religion
12    19         1)
((21, 0),     area  religion
52    21         0)
((21, 7),     area  religion
86    21         7)
((22, 2),     area  religion
47    22         2)
((23, 1),     area  religion
17    23         1)
((26, 5),      area  religion
143    26         5)
((28, 0),     area  religion
76    28         0)
((28, 5),     area  religion
29    28         5
53    28         5)
((29, 6),    area  religion
1    29         6)
((30, 1),      area  religion
151    30         1)
((30, 5),     area  religion
98    30         5)
((31, 0),     area  religion
16    31         0)
((36, 3),      area  religion
168    36         3)
((36, 5),     area  religion
74    36         5)
((41, 1),      area  religion
121    41         1
166    41         1)
((43, 1),     area  religion
46    43         1)
((47, 3),     area  religion
20    47         3)
((49, 0),     area  religion
49    49         0)
((51, 0),     area  religion
42    51         0)
((57, 7),      area  religion
171    57         7)
((63, 1),      area  religion
163    63         1)
((66, 3),      area  religion
157    66         3)
((70, 0),     area  religion
85    70         0)
((72, 5),      area  religion
149    72         5)
((76, 0),      area  religion
133    76         0)
((84, 0),     area  religion
11    84         0)
((84, 2),      area  religion
178    84         2)
((91, 0),     area  religion
60    91         0)
((92, 0),      area  religion
139    92         0)
((93, 6),     area  religion
79    93         6)
((98, 2),     area  religion
91    98         2)
((99, 7),      area  religion
154    99         7)
((103, 1),     area  religion
80   103         1)
((108, 6),     area  religion
64   108         6)
((109, 0),     area  religion
72   109         0)
((111, 5),     area  religion
99   111         5)
((111, 6),     area  religion
26   111         6)
((112, 0),     area  religion
77   112         0)
((113, 5),     area  religion
18   113         5)
((115, 6),     area  religion
43   115         6)
((118, 5),      area  religion
104   118         5)
((121, 6),      area  religion
128   121         6)
((128, 0),      area  religion
124   128         0)
((128, 6),     area  religion
45   128         6)
((132, 1),     area  religion
68   132         1)
((140, 4),      area  religion
120   140         4)
((143, 2),     area  religion
14   143         2)
((164, 2),      area  religion
174   164         2)
((178, 0),      area  religion
181   178         0)
((181, 3),     area  religion
92   181         3)
((185, 2),      area  religion
167   185         2)
((195, 2),      area  religion
129   195         2)
((196, 2),      area  religion
147   196         2)
((212, 2),      area  religion
131   212         2)
((215, 4),     area  religion
75   215         4)
((236, 5),      area  religion
179   236         5)
((236, 6),     area  religion
96   236         6)
((237, 6),      area  religion
142   237         6)
((239, 5),     area  religion
66   239         5)
((245, 1),      area  religion
180   245         1)
((246, 2),     area  religion
73   246         2)
((249, 1),     area  religion
65   249         1)
((256, 6),      area  religion
190   256         6)
((268, 1),      area  religion
123   268         1)
((268, 5),     area  religion
62   268         5)
((274, 5),     area  religion
27   274         5)
((284, 0),     area  religion
50   284         0)
((288, 2),      area  religion
155   288         2)
((300, 0),      area  religion
137   300         0)
((301, 0),     area  religion
87   301         0)
((313, 6),      area  religion
138   313         6)
((323, 5),     area  religion
88   323         5)
((324, 1),      area  religion
130   324         1)
((333, 2),      area  religion
105   333         2)
((333, 6),      area  religion
188   333         6)
((337, 1),     area  religion
58   337         1)
((342, 5),     area  religion
40   342         5)
((372, 7),     area  religion
90   372         7)
((391, 5),      area  religion
193   391         5)
((407, 0),      area  religion
135   407         0)
((435, 2),     area  religion
84   435         2)
((447, 2),      area  religion
117   447         2)
((450, 1),      area  religion
165   450         1)
((463, 5),      area  religion
134   463         5)
((474, 1),     area  religion
30   474         1)
((505, 0),      area  religion
156   505         0)
((514, 3),      area  religion
170   514         3)
((547, 0),     area  religion
59   547         0)
((583, 5),     area  religion
93   583         5)
((587, 1),      area  religion
103   587         1)
((600, 5),     area  religion
22   600         5)
((623, 5),     area  religion
34   623         5)
((637, 2),      area  religion
152   637         2)
((648, 2),    area  religion
0   648         2)
((678, 3),     area  religion
28   678         3)
((753, 5),      area  religion
192   753         5)
((757, 0),     area  religion
36   757         0)
((781, 2),      area  religion
175   781         2)
((783, 5),      area  religion
118   783         5)
((804, 2),      area  religion
132   804         2)
((905, 5),      area  religion
191   905         5)
((912, 0),      area  religion
187   912         0)
((925, 2),      area  religion
126   925         2)
((945, 5),      area  religion
169   945         5)
((1001, 2),     area  religion
51  1001         2)
((1031, 2),      area  religion
110  1031         2)
((1099, 0),     area  religion
21  1099         0)
((1139, 0),     area  religion
38  1139         0)
((1221, 1),      area  religion
153  1221         1)
((1222, 1),     area  religion
54  1222         1)
((1240, 2),      area  religion
107  1240         2)
((1247, 5),    area  religion
5  1247         5)
((1267, 2),      area  religion
125  1267         2)
((1284, 5),     area  religion
35  1284         5)
((1285, 0),      area  religion
136  1285         0)
((1566, 6),      area  religion
115  1566         6)
((1648, 2),     area  religion
83  1648         2)
((1760, 2),      area  religion
100  1760         2)
((1904, 2),     area  religion
82  1904         2)
((1973, 0),      area  religion
112  1973         0)
((2150, 2),      area  religion
146  2150         2)
((2176, 1),     area  religion
69  2176         1)
((2388, 2),    area  religion
2  2388         2)
((2506, 2),      area  religion
162  2506         2)
((2777, 0),    area  religion
8  2777         0
9  2777         0)
((3268, 4),     area  religion
81  3268         4)
((7690, 1),     area  religion
10  7690         1)
((8512, 0),     area  religion
23  8512         0)
((9363, 1),      area  religion
183  9363         1)
((9561, 6),     area  religion
37  9561         6)
((9976, 1),     area  religion
31  9976         1)
((22402, 6),       area  religion
184  22402         6)

In [14]:
grouped.size()

area   religion
0      0            7
       1           26
       2            1
1      1            3
       2            1
       3            2
2      2            1
       4            1
3      0            1
       1            1
4      0            2
5      1            1
6      2            1
9      0            1
       1            1
10     2            1
       5            1
11     1            1
       2            1
12     1            1
15     1            1
17     1            1
18     1            1
       2            1
19     1            1
21     0            1
       7            1
22     2            1
23     1            1
26     5            1
                   ..
925    2            1
945    5            1
1001   2            1
1031   2            1
1099   0            1
1139   0            1
1221   1            1
1222   1            1
1240   2            1
1247   5            1
1267   2            1
1284   5            1
1285   0            1
1566   6            1
1648   2            1
1760   2            1
1904   2            1
1973   0            1
2150   2            1
2176   1            1
2388   2            1
2506   2            1
2777   0            2
3268   4            1
7690   1            1
8512   0            1
9363   1            1
9561   6            1
9976   1            1
22402  6            1
Length: 156, dtype: int64

In [15]:
grouped.size().unstack(fill_value=0)

religion  0   1  2  3  4  5  6  7
area
0         7  26  1  0  0  0  0  0
1         0   3  1  2  0  0  0  0
2         0   0  1  0  1  0  0  0
3         1   1  0  0  0  0  0  0
4         2   0  0  0  0  0  0  0
5         0   1  0  0  0  0  0  0
6         0   0  1  0  0  0  0  0
9         1   1  0  0  0  0  0  0
10        0   0  1  0  0  1  0  0
11        0   1  1  0  0  0  0  0
12        0   1  0  0  0  0  0  0
15        0   1  0  0  0  0  0  0
17        0   1  0  0  0  0  0  0
18        0   1  1  0  0  0  0  0
19        0   1  0  0  0  0  0  0
21        1   0  0  0  0  0  0  1
22        0   0  1  0  0  0  0  0
23        0   1  0  0  0  0  0  0
26        0   0  0  0  0  1  0  0
28        1   0  0  0  0  2  0  0
29        0   0  0  0  0  0  1  0
30        0   1  0  0  0  1  0  0
31        1   0  0  0  0  0  0  0
36        0   0  0  1  0  1  0  0
41        0   2  0  0  0  0  0  0
43        0   1  0  0  0  0  0  0
47        0   0  0  1  0  0  0  0
49        1   0  0  0  0  0  0  0
51        1   0  0  0  0  0  0  0
57        0   0  0  0  0  0  0  1
...      ..  .. .. .. .. .. .. ..
925       0   0  1  0  0  0  0  0
945       0   0  0  0  0  1  0  0
1001      0   0  1  0  0  0  0  0
1031      0   0  1  0  0  0  0  0
1099      1   0  0  0  0  0  0  0
1139      1   0  0  0  0  0  0  0
1221      0   1  0  0  0  0  0  0
1222      0   1  0  0  0  0  0  0
1240      0   0  1  0  0  0  0  0
1247      0   0  0  0  0  1  0  0
1267      0   0  1  0  0  0  0  0
1284      0   0  0  0  0  1  0  0
1285      1   0  0  0  0  0  0  0
1566      0   0  0  0  0  0  1  0
1648      0   0  1  0  0  0  0  0
1760      0   0  1  0  0  0  0  0
1904      0   0  1  0  0  0  0  0
1973      1   0  0  0  0  0  0  0
2150      0   0  1  0  0  0  0  0
2176      0   1  0  0  0  0  0  0
2388      0   0  1  0  0  0  0  0
2506      0   0  1  0  0  0  0  0
2777      2   0  0  0  0  0  0  0
3268      0   0  0  0  1  0  0  0
7690      0   1  0  0  0  0  0  0
8512      1   0  0  0  0  0  0  0
9363      0   1  0  0  0  0  0  0
9561      0   0  0  0  0  0  1  0
9976      0   1  0  0  0  0  0  0
22402     0   0  0  0  0  0  1  0

[136 rows x 8 columns]

In [16]:
xgroup = grouped.size().unstack(fill_value=0).sum(axis = 1)
xgroup

area
0        34
1         6
2         2
3         2
4         2
5         1
6         1
9         2
10        2
11        2
12        1
15        1
17        1
18        2
19        1
21        2
22        1
23        1
26        1
28        3
29        1
30        2
31        1
36        2
41        2
43        1
47        1
49        1
51        1
57        1
         ..
925       1
945       1
1001      1
1031      1
1099      1
1139      1
1221      1
1222      1
1240      1
1247      1
1267      1
1284      1
1285      1
1566      1
1648      1
1760      1
1904      1
1973      1
2150      1
2176      1
2388      1
2506      1
2777      2
3268      1
7690      1
8512      1
9363      1
9561      1
9976      1
22402     1
Length: 136, dtype: int64

In [26]:
resultado = grouped.size().unstack(fill_value=0).iloc[0,:].values
resultado

array([ 7, 26,  1,  0,  0,  0,  0,  0])

In [18]:
print(resultado.sum())
resultado = resultado /34
resultado

34

array([0.20588235, 0.76470588, 0.02941176, 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [19]:
row = grouped.size().unstack(fill_value=0).iloc[0,:]
row[ row!= 0]

religion
0     7
1    26
2     1
Name: 0, dtype: int64

In [20]:
len(xgroup)amount_serie

SyntaxError: invalid syntax (<ipython-input-20-3a6f31157b17>, line 1)

In [ ]:
grouped.size().values

In [ ]:
len(grouped.size().values)

In [ ]:
tabla.sample(n=2, axis=1)[:5].join(tabla["religion"][:5])

In [ ]:
tabla.shape[1]

In [ ]:
isinstance(tabla,pd.DataFrame)

In [ ]:
tabla[tabla.columns[tabla.columns != "religion"]]#.join(tabla["religion"])
#tabla.columns[tabla.columns != "religion"]

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])
print(a,"\n")
print(b,"\n")
a[0,:]@b[:,0]